[project]
name = "04-sql-parse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "sqlfluff>=3.3.1",
    "sqlparse>=0.5.3",
    "streamlit>=1.42.1",
]
